version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - example_network
  example_app:
    build: .
    ports: 
      - "5050:5050"
    networks:
      - example_network

volumes:
  mongodb_data_container:
networks:
  example_network:
    name: example_network