@address = http://localhost:5050

@api = {{address}}/api


###
GET {{address}}/ping

###
POST {{api}}/examples
Content-Type: application/json

{
    "Content":"exampleContentValue"
}
###
@exampleId = 03987ad6-2afc-42f7-a385-a489006257da
###
GET {{api}}/examples/{{exampleId}}