@address = http://localhost:5050

@api = {{address}}/api


###
GET {{address}}/ping

###
POST {{api}}/examples
Content-Type: application/json

{
    "Content":"exampleContentValue"
}
###
@exampleId = ccebc08f-d6fa-4da2-afe5-73ff2bd75c40
###
GET {{api}}/examples/{{exampleId}}